### ISSUE TITLE
help Mr carlo

### ISSUE THREAD

**Issue by ghost** [carlo0815/openNFR-gui2#13]
hello friend please i tried to build your image to my dm800se and it build but the image block on spinner i want ask you please what is wrong in enigma2 binary file for to try fix it and thnx 
`root@dm800se:~# enigma2
PYTHONPATH: /usr/lib/enigma2/python
DVB_API_VERSION 5 DVB_API_VERSION_MINOR 4
11:40:28.087 + (1) Background File Eraser
11:40:28.088 + (5) Tuxtxt
11:40:28.088 + (8) graphics acceleration manager
11:40:28.093 + (9) Font Render Class
11:40:28.093 [FONT] initializing lib...
11:40:28.094 [FONT] loading fonts...
11:40:28.095 [FONT] Intializing font cache, using max. 4MB...
11:40:28.095 + (9) gLCDDC
/dev/fb1: No such file or directory
framebuffer not available.
11:40:28.096 found OLED display!
11:40:28.097 lcd buffer 0xf5dc50 12288 bytes, stride 192
11:40:28.097 LCD resolution: 96 x 64 x 16 (stride: 192)
11:40:28.097 + (9) GFBDC
11:40:28.097 16384k video mem
11:40:28.100  - double buffering available!
11:40:28.164 13144kB available for acceleration surfaces.
11:40:28.165 resolution: 720 x 576 x 32 (stride: 2880)
11:40:28.165 + (10) gRC
11:40:28.167 RC thread created successfully
11:40:28.167 + (15) eWindowStyleManager
11:40:28.167 + (20) AVSwitch Driver
11:40:28.167 couldnt open /dev/dbox/fp0 to monitor vcr scart slow blanking changed!
11:40:28.168 + (20) misc options
11:40:28.168 + (20) RC Input layer
11:40:28.168 + (20) UHF Modulator
11:40:28.168 couldnt open /dev/rfmod0!!!!
11:40:28.168 + (20) DVB-CI UI
11:40:28.168 + (21) input device driver
11:40:28.169 Input device "dreambox front panel" is a remotecontrol
11:40:28.170 Input device "dreambox remote control (native)" is a remotecontrol
11:40:28.170 Input device "dreambox advanced remote control (native)" is a remotecontrol
11:40:28.170 Input device "dreambox ir keyboard" is a keyboard
11:40:28.171 Input device "dreambox ir mouse" is a mouse
11:40:28.171 Found 5 input devices.
11:40:28.171 + (22) Hdmi CEC driver
11:40:28.171 eHdmiCEC: detected physical address change: 1000 --> 4000
11:40:28.171 eHdmiCEC: send message11:40:28.172  8411:40:28.172  4011:40:28.172  0011:40:28.172  0311:40:28.172  
11:40:28.172 + (30) eActionMap
11:40:28.172 + (35) CA handler
11:40:28.173 + (35) CI Slots
11:40:28.174 scanning for common interfaces..
11:40:28.174 cannot open /proc/stb/tsmux/input0
11:40:28.174 cannot open /proc/stb/tsmux/input1
11:40:28.175 done, found 0 common interface slots
11:40:28.175 + (40) eServiceCenter
11:40:28.175 settings instance.
11:40:28.175 + (41) Stream server
11:40:28.175 + (41) Encoders
11:40:28.176 + (41) eServiceFactoryDVB
11:40:28.176 + (41) eServiceFactoryFS
11:40:28.176 + (41) eServiceFactoryMP3
11:40:28.177 + (41) eServiceFactoryM2TS
11:40:28.177 + (41) eServiceFactoryHDMI
11:40:28.177 reached rl 70
11:40:28.177 ---- opening lame channel db
11:40:28.177 reading services (version 4)
11:40:29.217 loaded 470 channels/transponders and 11005 services
11:40:29.218 scanning for frontends..
11:40:29.219 opening frontend 0
11:40:29.228 try to close frontend 0
11:40:29.233 found 1 adapter, 1 frontends(1 sim) and 5 demux, boxtype 3
11:40:29.233 Use valid Linux Time :) (RTC?)
11:40:29.234 [EPGC] Initialized EPGCache (wait for setCacheFile call now)
11:40:29.237 Loading spinners...
11:40:29.381 [ePNG] couldn't open /usr/share/enigma2/spinner/wait37.png
11:40:29.381 found 36 spinner!
executing main
11:40:29.382 setIoPrio best-effort level 3 ok
11:40:30.171 couldn't open /proc/stb/misc/12V_output
[Harddisk] enumerating block devices...
11:40:30.268 main thread is non-idle! display spinner!
new Harddisk sda -> /dev/sda -> /dev/sda
[Harddisk] enumerating network mounts...
unable to load config ([Errno 2] No such file or directory: '/etc/enigma2/settings'), assuming defaults...
[openNFR] not loading user defined colors for skin
[openNFR] not loading user defined header file for skin
11:40:31.953 PC: 74a37188
11:40:31.953 00000000 00000001 77150000 28000076
11:40:31.954 7718458c 00000001 773ca6a4 0000019c
11:40:31.954 00000011 00000000 00000200 00002710
11:40:31.954 76bf4000 76bf9744 00000000 00000000
11:40:31.954 01509a68 01509a68 0150bd60 00000000
11:40:31.954 00000000 74a37138 01509a68 7676fdb0
11:40:31.954 00000004 00678570 6fffffff 00000000
11:40:31.954 771c62e0 7fbc9ef8 00e82850 74a37190
11:40:31.956 Backtrace:
11:40:31.957 enigma2(_Z17handleFatalSignaliP9siginfo_tPv) [0x45DE08]
11:40:31.957 /usr/lib/python2.7/lib-dynload/_hashlib.so(init_hashlib) [0x74A3718A]
11:40:31.957 -------FATAL SIGNAL
FONT 'Regular' MISSING!
FONT 'Regular' MISSING!
11:40:34.125 main thread is non-idle! display spinner!
Killed
`

**Comment by n3wb13** [comment]
"FATAL SIGNAL FONT 'Regular' MISSING! FONT 'Regular' MISSING! 11:40:34.125 main thread is non-idle! display spinner! Killed"

In your image / build is missing a font 'Regular'

**Comment by ghost** [comment]
thank you for the answear 

i use your files so i don't delet any font file

**Comment by n3wb13** [comment]
we don't need this font and therefore it does not exist with us. copy the font from another teamimage in your image and it runs
