### ISSUE TITLE
help

### ISSUE THREAD

**Issue by kingvuplus** [carlo0815/openNFR-gui2#5]
please can you make one nfrboot for mipsel and spark

**Comment by carlo0815** [comment]
we have one for mipsel and one for sh4 (spark)

**Comment by kingvuplus** [comment]
thank s for reply 

i have solo2 and i am devlopeur for Spark Box but i dont have the spark box for test 
i want test image of spark with nfrBoot on my solo2 directly

**Comment by carlo0815** [comment]
your are sparkdeveloper?

But you don't know that sh4 image you can't test on Mipselbox?
As sample enigma2 binary ist sh4 compiled and can't run on solo2 and you have not only one compiled binary in image. Driver can't be test, Display can't be test .......

What you want can't work!

If you want be a Spark-Developer you need a Sparkbox.
