### ISSUE TITLE
packagedata

### ISSUE THREAD

**Issue by elhawaryna** [carlo0815/openNFR-gui2#80]
hello
`ERROR: enigma2-plugins-6.4+gitAUTOINC+fc1ab145ce-r0 do_packagedata: The recipe enigma2-plugins is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
  /home/elhawary/build-enviroment/builds/opennfr/release/dm820/tmp/pkgdata/dm820/runtime/enigma2-plugin-extensions-bmediacenter-src
    (matched in manifest-dm820-enigma2.packagedata)
  /home/elhawary/build-enviroment/builds/opennfr/release/dm820/tmp/pkgdata/dm820/runtime/enigma2-plugin-extensions-menusort-src.packaged
    (matched in manifest-dm820-enigma2.packagedata)
  /home/elhawary/build-enviroment/builds/opennfr/release/dm820/tmp/pkgdata/dm820/runtime/enigma2-plugin-extensions-bmediacenter.packaged
    (matched in manifest-dm820-enigma2.packagedata)
  /home/elhawary/build-enviroment/builds/opennfr/release/dm820/tmp/pkgdata/dm820/runtime/enigma2-plugin-extensions-bmediacenter
    (matched in manifest-dm820-enigma2.packagedata)
  /home/elhawarye/build-enviroment/builds/opennfr/release/dm820/tmp/pkgdata/dm820/runtime/enigma2-plugin-extensions-menusort.packaged
    (matched in manifest-dm820-enigma2.packagedata)
  /home/elhawary/build-enviroment/builds/opennfr/release/dm820/tmp/pkgdata/dm820/runtime/enigma2-plugin-extensions-menusort
    (matched in manifest-dm820-enigma2.packagedata)
  /home/elhawary/build-enviroment/builds/opennfr/release/dm820/tmp/pkgdata/dm820/runtime/enigma2-plugin-extensions-bmediacenter-src.packaged
    (matched in manifest-dm820-enigma2.packagedata)
  /home/elhawary/build-enviroment/builds/opennfr/release/dm820/tmp/pkgdata/dm820/runtime/enigma2-plugin-extensions-menusort-src
    (matched in manifest-dm820-enigma2.packagedata)
Please verify which recipe should provide the above files.

The build has stopped, as continuing in this scenario WILL break things - if not now, possibly in the future (we've seen builds fail several months later). If the system knew how to recover from this automatically it would, however there are several different scenarios which can result in this and we don't know which one this is. It may be you have switched providers of something like virtual/kernel (e.g. from linux-yocto to linux-yocto-dev), in that case you need to execute the clean task for both recipes and it will resolve this error. It may be you changed DISTRO_FEATURES from systemd to udev or vice versa. Cleaning those recipes should again resolve this error, however switching DISTRO_FEATURES on an existing build directory is not supported - you should really clean out tmp and rebuild (reusing sstate should be safe). It could be the overlapping files detected are harmless in which case adding them to SSTATE_DUPWHITELIST may be the correct solution. It could also be your build is including two different conflicting versions of things (e.g. bluez 4 and bluez 5 and the correct solution for that would be to resolve the conflict. If in doubt, please ask on the mailing list, sharing the error and filelist above.
ERROR: enigma2-plugins-6.4+gitAUTOINC+fc1ab145ce-r0 do_packagedata: If the above message is too much, the simpler version is you're advised to wipe out tmp and rebuild (reusing sstate is fine). That will likely fix things in most (but not all) cases.
ERROR: Logfile of failure stored in: /home/elhawary/teamblue/build-enviroment/builds/opennfr/release/dm820/tmp/work/dm820-oe-linux/enigma2-plugins/6.4+gitAUTOINC+fc1ab145ce-r0/temp/log.do_packagedata.30288
ERROR: Task (/home/elhawary/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2-plugins/enigma2-plugins.bb:do_packagedata) failed with exit code '1'
NOTE: Tasks Summary: Attempted 6384 tasks of which 4794 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/elhawary/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2-plugins/enigma2-plugins.bb:do_packagedata
Summary: There were 54 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
Makefile:1048: recipe for target 'image' failed
make: *** [image] Error 1
`

**Comment by carlo0815** [comment]
this is not a issue because we don't build Dreambox and not support it

**Comment by elhawaryna** [comment]
Danke für diese Antwort

**Comment by carlo0815** [comment]
Nix zu Danken
